### ISSUE TITLE
yarn serve fails to compile with 3 errors

### ISSUE THREAD

**Issue by NodeGuy** [tendermint/ui#68]
```
$ git clone git@github.com:tendermint/ui.git
Cloning into 'ui'...
remote: Counting objects: 1692, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1692 (delta 1), reused 3 (delta 0), pack-reused 1677
Receiving objects: 100% (1692/1692), 1.24 MiB | 532.00 KiB/s, done.
Resolving deltas: 100% (931/931), done.
$ cd ui
$ yarn install
yarn install v1.9.4
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.3" has unmet peer dependency "webpack@>=2".
warning "@vue/cli-plugin-eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
warning "@vue/eslint-config-prettier > eslint-config-prettier@2.9.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] 📃  Building fresh packages...
✨  Done in 12.68s.
$ yarn serve
yarn run v1.9.4
warning ../package.json: No license field
$ vue-cli-service serve
 INFO  Starting development server...
 94% after seal                                                                       

 ERROR  Failed to compile with 3 errors                                                                                                               12:04:21

Module build failed (from ./node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js):
Error: 

Vue packages version mismatch:

- vue@2.5.17
- vue-template-compiler@2.5.16

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/david/Documents/AllInBits/ui/node_modules/@vue/cli-service/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.module.exports (/Users/david/Documents/AllInBits/ui/node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js:54:35)

Module build failed (from ./node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js):
Error: 

Vue packages version mismatch:

- vue@2.5.17
- vue-template-compiler@2.5.16

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/david/Documents/AllInBits/ui/node_modules/@vue/cli-service/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.module.exports (/Users/david/Documents/AllInBits/ui/node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js:54:35)

Module build failed (from ./node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js):
Error: 

Vue packages version mismatch:

- vue@2.5.17
- vue-template-compiler@2.5.16

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/david/Documents/AllInBits/ui/node_modules/@vue/cli-service/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.module.exports (/Users/david/Documents/AllInBits/ui/node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js:54:35)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

**Comment by faboweb** [comment]
Lets fix versions: https://github.com/tendermint/ui/blob/develop/package.json#L45

**Comment by lovincyrus** [comment]
Closed because of https://github.com/tendermint/ui/pull/95
